"""Editorial export subsystem (PRD §15.4, §11.1, §13.1, §19.2, §1.3.7).

Turns a project's ``translation_units`` + ``structure_nodes`` + ``tm_entries``
into downloadable artifacts, each carrying the §15.4 manifest:

* **Editorial book** (``docx`` / ``epub`` / ``html``) -- the finished
  translation with chapter structure and markup preserved.
* **CAT bilingual** (``xliff`` / ``tmx`` / ``csv``) -- XLIFF 2.1 (segments
  with state, validated against the OASIS XSD), TMX 1.4 of the approved TM
  (validated against the LISA DTD), and a plain bilingual CSV, all
  re-importable through :mod:`~.export.reimport`.

Design rules encoded here:

* **§15.4 gating** -- an export is either *approved-only* (every returned
  segment is ``approved``) or a *drafts* export whose segments are all
  flagged ``draft`` and carry an explicit watermark. A project with *no*
  approved segments can only be exported with ``include_drafts=True`` and
  then only with the watermark forced on.
* **§15.4 manifest** -- every export carries a manifest with project
  version, timestamp, segment counts, the model(s) used and the glossary/TM
  snapshots that were current at export time.
* **§13.1 audit** -- each export writes one append-only ``audit_log`` row.
* **local-only** -- the generated bytes never leave the process; the route
  streams them to the browser through the Next origin rewrite.
"""
from __future__ import annotations

from .collector import (
    ExportSegment,
    Exporter,
    LoadError,
    build_exporter,
)
from .errors import (
    ExportError,
    NoApprovedSegments,
    WatermarkRequired,
)
from .manifest import (
    ExportManifest,
    build_manifest,
)
from .docx_export import write_docx
from .epub_export import write_epub
from .epub_clone_export import write_epub_clone
from .html_export import write_html
from .markup import render_inline
from .pdf_clone_export import write_pdf_clone
from .pdf_export import write_pdf
from .xliff_export import (
    read_xliff,
    state_to_status,
    status_to_state,
    write_xliff,
)
from .tmx_export import (
    read_tmx,
    write_tmx,
)
from .csv_export import (
    read_csv,
    write_csv,
)
from .reimport import (
    REIMPORTS,
    reimport_csv,
    reimport_tmx,
    reimport_xliff,
)
from .validate import (
    validate_tmx,
    validate_xliff,
)

__all__ = [
    "Exporter",
    "ExportSegment",
    "build_exporter",
    "ExportError",
    "LoadError",
    "NoApprovedSegments",
    "WatermarkRequired",
    "ExportManifest",
    "build_manifest",
    "write_docx",
    "write_epub",
    "write_epub_clone",
    "write_html",
    "render_inline",
    # CAT formats
    "write_xliff",
    "read_xliff",
    "status_to_state",
    "state_to_status",
    "write_tmx",
    "read_tmx",
    "write_csv",
    "read_csv",
    # re-import
    "REIMPORTS",
    "reimport_xliff",
    "reimport_csv",
    "reimport_tmx",
    # validation
    "validate_xliff",
    "validate_tmx",
]
