"""001 initial schema

Revision ID: 37c136b20943
Revises: 
Create Date: 2026-09-02 21:08:51.451516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '37c136b20943'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_action', ['action'], unique=False)
        batch_op.create_index('ix_audit_created', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_project', ['project_id'], unique=False)
        batch_op.create_index('ix_audit_user', ['user_id'], unique=False)

    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('source_language', sa.CHAR(length=2), nullable=False),
    sa.Column('target_language', sa.CHAR(length=2), nullable=False),
    sa.Column('genre_profile', sa.String(length=128), nullable=False),
    sa.Column('translation_model_id', sa.String(length=255), nullable=True),
    sa.Column('text_model_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index('ix_projects_languages', ['source_language', 'target_language'], unique=False)
        batch_op.create_index('ix_projects_status', ['status'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_email', ['email'], unique=False)

    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('canonical_source', sa.Text(), nullable=False),
    sa.Column('canonical_target', sa.Text(), nullable=True),
    sa.Column('entity_type', sa.String(length=48), nullable=False),
    sa.Column('referential_gender', sa.String(length=24), nullable=False),
    sa.Column('referential_gender_evidence', sa.String(length=255), nullable=True),
    sa.Column('italian_grammatical_gender', sa.String(length=24), nullable=False),
    sa.Column('grammatical_number', sa.String(length=24), nullable=False),
    sa.Column('translation_policy', sa.String(length=24), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.create_index('ix_entities_project', ['project_id'], unique=False)
        batch_op.create_index('ix_entities_status', ['status'], unique=False)
        batch_op.create_index('ix_entities_type', ['entity_type'], unique=False)

    op.create_table('glossary_terms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_term', sa.Text(), nullable=False),
    sa.Column('target_term', sa.Text(), nullable=True),
    sa.Column('term_type', sa.String(length=48), nullable=False),
    sa.Column('preferred', sa.BOOLEAN(), nullable=False),
    sa.Column('forbidden_targets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grammatical_gender_it', sa.String(length=24), nullable=True),
    sa.Column('grammatical_number', sa.String(length=24), nullable=True),
    sa.Column('inflection_notes', sa.Text(), nullable=True),
    sa.Column('usage_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('glossary_terms', schema=None) as batch_op:
        batch_op.create_index('ix_glossary_project', ['project_id'], unique=False)
        batch_op.create_index('ix_glossary_status', ['status'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index('ix_jobs_project', ['project_id'], unique=False)
        batch_op.create_index('ix_jobs_status', ['status'], unique=False)

    op.create_table('llm_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('run_type', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_hash', sa.String(length=64), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.create_index('ix_llm_runs_model', ['model_name'], unique=False)
        batch_op.create_index('ix_llm_runs_project', ['project_id'], unique=False)
        batch_op.create_index('ix_llm_runs_status', ['status'], unique=False)

    op.create_table('memory_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_type', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshot_project', ['project_id'], unique=False)
        batch_op.create_index('ix_snapshot_type', ['snapshot_type'], unique=False)

    op.create_table('structure_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('source_label', sa.String(length=255), nullable=True),
    sa.Column('normalized_title', sa.Text(), nullable=True),
    sa.Column('start_page', sa.Integer(), nullable=True),
    sa.Column('end_page', sa.Integer(), nullable=True),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('detection_method', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['structure_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'ordinal', name='ux_structure_node_project_ordinal')
    )
    with op.batch_alter_table('structure_nodes', schema=None) as batch_op:
        batch_op.create_index('ix_structure_node_kind', ['kind'], unique=False)
        batch_op.create_index('ix_structure_node_parent', ['parent_id'], unique=False)
        batch_op.create_index('ix_structure_node_project', ['project_id'], unique=False)

    op.create_table('tm_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('scene_id', sa.UUID(), nullable=True),
    sa.Column('source_normalized', sa.Text(), nullable=False),
    sa.Column('source_original', sa.Text(), nullable=False),
    sa.Column('target_approved', sa.Text(), nullable=False),
    sa.Column('genre_profile', sa.String(length=128), nullable=True),
    sa.Column('pov', sa.String(length=128), nullable=True),
    sa.Column('reviewer', sa.String(length=128), nullable=True),
    sa.Column('qa_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('terms_used', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_embedding', Vector(768), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tm_entries', schema=None) as batch_op:
        batch_op.create_index('ix_tm_project', ['project_id'], unique=False)
        batch_op.create_index('ix_tm_source_normalized', ['source_normalized'], unique=False)

    op.create_table('translation_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('target_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('glossary_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('tm_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('model_run_id', sa.UUID(), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'chapter_id', 'ordinal', name='ux_tu_project_chapter_ordinal')
    )
    with op.batch_alter_table('translation_units', schema=None) as batch_op:
        batch_op.create_index('ix_tu_project', ['project_id'], unique=False)
        batch_op.create_index('ix_tu_status', ['status'], unique=False)

    op.create_table('entity_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('source_alias', sa.Text(), nullable=False),
    sa.Column('target_alias', sa.Text(), nullable=True),
    sa.Column('alias_type', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'source_alias', name='ux_entity_alias_entity_source')
    )
    with op.batch_alter_table('entity_aliases', schema=None) as batch_op:
        batch_op.create_index('ix_entity_alias_entity', ['entity_id'], unique=False)

    op.create_table('entity_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('chapter_id', sa.UUID(), nullable=True),
    sa.Column('source_segment_id', sa.UUID(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('quote_text', sa.Text(), nullable=False),
    sa.Column('evidence_type', sa.String(length=48), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('extractor', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity_evidence', schema=None) as batch_op:
        batch_op.create_index('ix_entity_evidence_entity', ['entity_id'], unique=False)
        batch_op.create_index('ix_entity_evidence_page', ['page_number'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity_evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_evidence_page')
        batch_op.drop_index('ix_entity_evidence_entity')

    op.drop_table('entity_evidence')
    with op.batch_alter_table('entity_aliases', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_alias_entity')

    op.drop_table('entity_aliases')
    with op.batch_alter_table('translation_units', schema=None) as batch_op:
        batch_op.drop_index('ix_tu_status')
        batch_op.drop_index('ix_tu_project')

    op.drop_table('translation_units')
    with op.batch_alter_table('tm_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_tm_source_normalized')
        batch_op.drop_index('ix_tm_project')

    op.drop_table('tm_entries')
    with op.batch_alter_table('structure_nodes', schema=None) as batch_op:
        batch_op.drop_index('ix_structure_node_project')
        batch_op.drop_index('ix_structure_node_parent')
        batch_op.drop_index('ix_structure_node_kind')

    op.drop_table('structure_nodes')
    with op.batch_alter_table('memory_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_type')
        batch_op.drop_index('ix_snapshot_project')

    op.drop_table('memory_snapshots')
    with op.batch_alter_table('llm_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_llm_runs_status')
        batch_op.drop_index('ix_llm_runs_project')
        batch_op.drop_index('ix_llm_runs_model')

    op.drop_table('llm_runs')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_jobs_status')
        batch_op.drop_index('ix_jobs_project')

    op.drop_table('jobs')
    with op.batch_alter_table('glossary_terms', schema=None) as batch_op:
        batch_op.drop_index('ix_glossary_status')
        batch_op.drop_index('ix_glossary_project')

    op.drop_table('glossary_terms')
    with op.batch_alter_table('entities', schema=None) as batch_op:
        batch_op.drop_index('ix_entities_type')
        batch_op.drop_index('ix_entities_status')
        batch_op.drop_index('ix_entities_project')

    op.drop_table('entities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')

    op.drop_table('users')
    op.drop_table('roles')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index('ix_projects_status')
        batch_op.drop_index('ix_projects_languages')

    op.drop_table('projects')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_user')
        batch_op.drop_index('ix_audit_project')
        batch_op.drop_index('ix_audit_created')
        batch_op.drop_index('ix_audit_action')

    op.drop_table('audit_log')
    # ### end Alembic commands ###
